name: annova
version: 1.0.0+1
description: Annova campus-focused social marketplace app for Android, iOS, and Web.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^6.0.0
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.1.1
  firebase_storage: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
